/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcp_bindings_libsvm_svm */

#ifndef _Included_jcp_bindings_libsvm_svm
#define _Included_jcp_bindings_libsvm_svm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_train
 * Signature: (Ljcp/bindings/libsvm/svm_problem;Ljcp/bindings/libsvm/svm_parameter;)J
 */
JNIEXPORT jlong JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1train
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_cross_validation
 * Signature: (Ljcp/bindings/libsvm/svm_problem;Ljcp/bindings/libsvm/svm_parameter;I[D)V
 */
JNIEXPORT void JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1cross_1validation
  (JNIEnv *, jclass, jobject, jobject, jint, jdoubleArray);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_get_svm_type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1get_1svm_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_get_nr_class
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1get_1nr_1class
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_get_labels
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1get_1labels
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_get_sv_indices
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1get_1sv_1indices
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_get_nr_sv
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1get_1nr_1sv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_get_svr_probability
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1get_1svr_1probability
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_predict_values
 * Signature: (J[Ljcp/bindings/libsvm/svm_node;[D)D
 */
JNIEXPORT jdouble JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1predict_1values
  (JNIEnv *, jclass, jlong, jobjectArray, jdoubleArray);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_predict
 * Signature: (J[Ljcp/bindings/libsvm/svm_node;)D
 */
JNIEXPORT jdouble JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1predict
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_predict_probability
 * Signature: (J[Ljcp/bindings/libsvm/svm_node;[D)D
 */
JNIEXPORT jdouble JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1predict_1probability
  (JNIEnv *, jclass, jlong, jobjectArray, jdoubleArray);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_save_model
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1save_1model
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_load_model
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1load_1model
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_check_parameter
 * Signature: (Ljcp/bindings/libsvm/svm_problem;Ljcp/bindings/libsvm/svm_parameter;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1check_1parameter
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     jcp_bindings_libsvm_svm
 * Method:    native_svm_check_probability_model
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jcp_bindings_libsvm_svm_native_1svm_1check_1probability_1model
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
