/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_hb_jcp_bindings_libsvm_svm_problem */

#ifndef _Included_se_hb_jcp_bindings_libsvm_svm_problem
#define _Included_se_hb_jcp_bindings_libsvm_svm_problem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_hb_jcp_bindings_libsvm_svm_problem
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_se_hb_jcp_bindings_libsvm_svm_1problem_native_1init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
