/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D */

#ifndef _Included_se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D
#define _Included_se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D
#ifdef __cplusplus
extern "C" {
#endif
#undef se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D_serialVersionUID
#define se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D_serialVersionUID 1020LL
/*
 * Class:     se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D
 * Method:    native_vector_create
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D_native_1vector_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D
 * Method:    native_vector_free
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D_native_1vector_1free
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D
 * Method:    native_vector_create_from
 * Signature: ([I[D)J
 */
JNIEXPORT jlong JNICALL Java_se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D_native_1vector_1create_1from
  (JNIEnv *, jclass, jintArray, jdoubleArray);

/*
 * Class:     se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D
 * Method:    native_vector_assign
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D_native_1vector_1assign
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D
 * Method:    native_vector_get
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D_native_1vector_1get
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D
 * Method:    native_vector_set
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_se_hb_jcp_bindings_libsvm_SparseDoubleMatrix1D_native_1vector_1set
  (JNIEnv *, jclass, jlong, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
