/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_hb_jcp_bindings_libsvm_svm_model */

#ifndef _Included_se_hb_jcp_bindings_libsvm_svm_model
#define _Included_se_hb_jcp_bindings_libsvm_svm_model
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_hb_jcp_bindings_libsvm_svm_model
 * Method:    native_free_svm_model
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_se_hb_jcp_bindings_libsvm_svm_1model_native_1free_1svm_1model
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
