/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_hb_jcp_bindings_libsvm_svm */

#ifndef _Included_se_hb_jcp_bindings_libsvm_svm
#define _Included_se_hb_jcp_bindings_libsvm_svm
#ifdef __cplusplus
extern "C" {
#endif
#undef se_hb_jcp_bindings_libsvm_svm_DEBUG
#define se_hb_jcp_bindings_libsvm_svm_DEBUG 0L
/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_train
 * Signature: (Lse/hb/jcp/bindings/libsvm/svm_problem;Lse/hb/jcp/bindings/libsvm/svm_parameter;)J
 */
JNIEXPORT jlong JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1train
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_train_fast
 * Signature: (Lse/hb/jcp/bindings/libsvm/svm_parameter;J[D)J
 */
JNIEXPORT jlong JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1train_1fast
  (JNIEnv *, jclass, jobject, jlong, jdoubleArray);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_cross_validation
 * Signature: (Lse/hb/jcp/bindings/libsvm/svm_problem;Lse/hb/jcp/bindings/libsvm/svm_parameter;I[D)V
 */
JNIEXPORT void JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1cross_1validation
  (JNIEnv *, jclass, jobject, jobject, jint, jdoubleArray);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_get_svm_type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1get_1svm_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_get_nr_class
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1get_1nr_1class
  (JNIEnv *, jclass, jlong);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_get_labels
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1get_1labels
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_get_sv_indices
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1get_1sv_1indices
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_get_nr_sv
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1get_1nr_1sv
  (JNIEnv *, jclass, jlong);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_get_svr_probability
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1get_1svr_1probability
  (JNIEnv *, jclass, jlong);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_predict_values
 * Signature: (J[Lse/hb/jcp/bindings/libsvm/svm_node;[D)D
 */
JNIEXPORT jdouble JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1predict_1values
  (JNIEnv *, jclass, jlong, jobjectArray, jdoubleArray);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_predict
 * Signature: (J[Lse/hb/jcp/bindings/libsvm/svm_node;)D
 */
JNIEXPORT jdouble JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1predict
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_predict_fast
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1predict_1fast
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_predict_probability
 * Signature: (J[Lse/hb/jcp/bindings/libsvm/svm_node;[D)D
 */
JNIEXPORT jdouble JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1predict_1probability
  (JNIEnv *, jclass, jlong, jobjectArray, jdoubleArray);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_predict_probability_fast
 * Signature: (JJ[D)D
 */
JNIEXPORT jdouble JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1predict_1probability_1fast
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_save_model
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1save_1model
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_load_model
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1load_1model
  (JNIEnv *, jclass, jstring);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_check_parameter
 * Signature: (Lse/hb/jcp/bindings/libsvm/svm_problem;Lse/hb/jcp/bindings/libsvm/svm_parameter;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1check_1parameter
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_check_parameter_fast
 * Signature: (Lse/hb/jcp/bindings/libsvm/svm_parameter;J[D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1check_1parameter_1fast
  (JNIEnv *, jclass, jobject, jlong, jdoubleArray);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_check_probability_model
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1check_1probability_1model
  (JNIEnv *, jclass, jlong);

/*
 * Class:     se_hb_jcp_bindings_libsvm_svm
 * Method:    native_svm_distance_from_separating_plane
 * Signature: (JJJ)D
 */
JNIEXPORT jdouble JNICALL Java_se_hb_jcp_bindings_libsvm_svm_native_1svm_1distance_1from_1separating_1plane
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
