/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_hb_jcp_bindings_libsvm_svm_parameter */

#ifndef _Included_se_hb_jcp_bindings_libsvm_svm_parameter
#define _Included_se_hb_jcp_bindings_libsvm_svm_parameter
#ifdef __cplusplus
extern "C" {
#endif
#undef se_hb_jcp_bindings_libsvm_svm_parameter_C_SVC
#define se_hb_jcp_bindings_libsvm_svm_parameter_C_SVC 0L
#undef se_hb_jcp_bindings_libsvm_svm_parameter_NU_SVC
#define se_hb_jcp_bindings_libsvm_svm_parameter_NU_SVC 1L
#undef se_hb_jcp_bindings_libsvm_svm_parameter_ONE_CLASS
#define se_hb_jcp_bindings_libsvm_svm_parameter_ONE_CLASS 2L
#undef se_hb_jcp_bindings_libsvm_svm_parameter_EPSILON_SVR
#define se_hb_jcp_bindings_libsvm_svm_parameter_EPSILON_SVR 3L
#undef se_hb_jcp_bindings_libsvm_svm_parameter_NU_SVR
#define se_hb_jcp_bindings_libsvm_svm_parameter_NU_SVR 4L
#undef se_hb_jcp_bindings_libsvm_svm_parameter_LINEAR
#define se_hb_jcp_bindings_libsvm_svm_parameter_LINEAR 0L
#undef se_hb_jcp_bindings_libsvm_svm_parameter_POLY
#define se_hb_jcp_bindings_libsvm_svm_parameter_POLY 1L
#undef se_hb_jcp_bindings_libsvm_svm_parameter_RBF
#define se_hb_jcp_bindings_libsvm_svm_parameter_RBF 2L
#undef se_hb_jcp_bindings_libsvm_svm_parameter_SIGMOID
#define se_hb_jcp_bindings_libsvm_svm_parameter_SIGMOID 3L
#undef se_hb_jcp_bindings_libsvm_svm_parameter_PRECOMPUTED
#define se_hb_jcp_bindings_libsvm_svm_parameter_PRECOMPUTED 4L
/*
 * Class:     se_hb_jcp_bindings_libsvm_svm_parameter
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_se_hb_jcp_bindings_libsvm_svm_1parameter_native_1init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
